version: '3'
services:
  db:
    image: postgres:16.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data 

  app:
    image: guibitencurt/spring-boot-api-ci:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_api
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  pg_data: